defaults:
  - _self_
  - data: default
  - networks: null
  - optimizer: adam
  - scheduler: null
  - model: null
  - trainer: default
  - callbacks: default
  - logger: wandb
  - paths: default
  - seed: default

  - experiment: null

hydra:
  job:
    name: ${task_name}
  output_subdir: config
  run:
    dir: runs/${hydra.job.name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
  sweep:
    dir: runs/${hydra.job.name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
    subdir: ${hydra.job.override_dirname}

task_name: exp
train: True
test: False